### ISSUE TITLE
6.0.8 Stable Atlantis Release Tracker

### ISSUE THREAD

**Issue by soc1c** [etclabscore/go-ethereum#35]
- [ ] Import paths (#3)
- [ ] Add whiteblock config/script (#11)
- [x] For the same txid, why is the "status" returned from getTransactionReceipt different between versions 5.5.2 and 6.0.6? (#23)
- [x] Storage and edge case fixes (#28)
- [x] Replace repository reference for accounts/abi/bind (#29)
- [ ] X-Compile to Windows and MacOS (#32)
- [x] Tx Encoding and decoding fix (#33)
- [x] Docs: update badges (#34)
- [ ] change import paths, again, fix #3 (#36)

**Comment by soc1c** [comment]
Sanity checks

Kensington Block Hash / Number
- [x] Parity-Ethereum 2.5.5 :heavy_check_mark: 426723 **0x7e62…dd37**
    ```
    2019-08-13 09:05:01  Imported #426723 0x7e62…dd37 (1 txs, 0.21 Mgas, 1 ms, 1.86 KiB)
    ```
- [x] Parity-Ethereum 2.6.0 :heavy_check_mark: 426723 **0x7e62…dd37**
    ```
    2019-08-13 09:05:01  Imported #426723 0x7e62…dd37 (1 txs, 0.21 Mgas, 1 ms, 1.86 KiB)
    ```
- [x] Multi-Geth 1.9.2 :heavy_check_mark: number=426723 hash=**7e62da…09dd37**
    ```
    INFO [08-13|09:05:01.536] Imported new chain segment               blocks=1    txs=1    mgas=0.210   elapsed=18.534ms  mgasps=11.330  number=426723 hash=7e62da…09dd37 dirty=756.00KiB
    ```
- [x] Multi-Geth 1.9.0/feat/chainspec :heavy_check_mark: number=426723 hash=**7e62da…09dd37**
    ```
    INFO [08-13|09:05:01.512] Imported new chain segment               blocks=1    txs=1    mgas=0.210   elapsed=10.713ms  mgasps=19.601  number=426723 hash=7e62da…09dd37 dirty=1.00MiB                                                                                                                                          
    ```
- [x] Geth-Classic 6.0.7 :heavy_check_mark: 426723 **7e62dadc**
    ```
    2019-08-13 09:05:01 Mined    #426723                7e62dadc          1/ 0 txs/mgas          3/25 peers
    ```

Kotti Block Hash / Number
- [x] Parity-Ethereum 2.5.5 :heavy_check_mark: 1024665 **0xcfe0…a7e5**
    ```
    2019-08-12 17:41:59  Imported #1024665 0xcfe0…a7e5 (0 txs, 0.00 Mgas, 0 ms, 0.59 KiB)
    ```
- [x] Parity-Ethereum 2.6.0 :heavy_check_mark: 1024665 **0xcfe0…a7e5**
    ```
    2019-08-12 17:41:59  Imported #1024665 0xcfe0…a7e5 (0 txs, 0.00 Mgas, 0 ms, 0.59 KiB)
    ```
- [x] Multi-Geth 1.9.2 :heavy_check_mark: number=1024665 hash=**cfe037…68a7e5**
    ```
    INFO [08-12|17:41:59.604] Imported new chain segment               blocks=1    txs=0 mgas=0.000 elapsed=448.621µs mgasps=0.000 number=1024665 hash=cfe037…68a7e5 dirty=0.00B
    ```

Morden Block Hash / Number
- [x] Parity-Ethereum 2.5.5 :heavy_check_mark: 4807215 **0x1cdd…a5f4**
    ```
    2019-08-12 17:47:14  Imported #4807215 0x1cdd…a5f4 (35 txs, 2.76 Mgas, 28 ms, 10.13 KiB)
    ```
- [x] Parity-Ethereum 2.6.0 :heavy_check_mark: 4807215 **0x1cdd…a5f4**
    ```
    2019-08-12 17:47:14  Imported #4807215 0x1cdd…a5f4 (35 txs, 2.76 Mgas, 28 ms, 10.13 KiB)
    ```
- [x] Geth-Classic 6.0.7 :heavy_check_mark: 4807215 **1cdd2ca7**
    ```
    2019-08-12 17:47:14 Import    #4807215              1cdd2ca7         35/ 2 txs/mgas          2/25 peers
    ```

**Comment by soc1c** [comment]
https://www.youtube.com/watch?v=ghNqMLYAVKc

**Comment by soc1c** [comment]
https://medium.com/@a4fri/state-of-the-atlantis-testnets-dc1cf61fc44

**Comment by GregTheGreek** [comment]
Closing in favour of #39 .
Ported over issues to new release patch 6.0.9
