### ISSUE TITLE
6.0.10 Release Tracker (Nice to haves)

### ISSUE THREAD

**Issue by GregTheGreek** [etclabscore/go-ethereum#39]
- [ ] Import paths (#3)
- [x] Add whiteblock config/script (#11)
- [ ] X-Compile to Windows and MacOS (#32)
- [ ] change import paths, again, fix #3 (#36)
- [x] updated TestParseNode to work with go v1.12.8 (#42)
